- avgsamplerate_test.go
- avgsamplewithmin_test.go
- onlyonce_test.go
- perkeythroughput_test.go
- static_test.go
- totalthroughput_test.go
Depending on honeycombio/hound/test causes interesting results when trying to
vendor this library in another project. Use the `assert` package from
github.com/stretchr/testify instead.
> Replace use of home-grown test helpers

- avgsamplerate.go
- avgsamplerate_test.go
- avgsamplewithmin.go
- avgsamplewithmin_test.go
When starting a new process using the dynsampler, the old behavior was to treat every key as though it had not been seen and give it a sample rate of 1 for the first 30 seconds. The effect is that when dealing with high volume services, you sent a very large amount of traffic for the first 30 seconds. 
Instead of treating the startup period as though we were in a low volume setting, let's just use the goal sample rate on all traffic until we've gotten the first sample of traffic from which we can compute the dynamic sample rate.
> use the goal sample rate on startup

- avgsamplewithmin.go
While porting dynsampler-go to ruby (WIP here https://github.com/travis-ci/dynsampler-rb) I noticed a missing lock.
Perhaps I'm missing something, and it is not needed in this case. But it certainly looked suspicious. :)
> add missing locking to AvgSampleWithMin

- avgsamplerate.go
- avgsamplerate_test.go
- avgsamplewithmin.go
- avgsamplewithmin_test.go
Step 1 in fixing https://github.com/honeycombio/honeytail/issues/123.
I am not really clear on the use of log10 to compute the "goalRatio" for each key in the dynamic sampler, but one issue can occur if all counts in any given interval are <= 1:
```
for _, count := range tmpCounts {
logSum += math.Log10(float64(count))
}
```
In this case, logSum is 0, so when goalRatio is computed:
```
goalRatio := goalCount / logSum
```
We get `+Inf` and ultimately return `int(NaN)` as the rate - causing `-9223372036854775808` to get passed to `rand.Intn` and a panic.
To prevent this, we can fallback to a rate of 1 if we compute NaN for goalRatio - which seems OK if all event counts are small.
> Handle case where NaN values are computed in dynamic sampler

- avgsamplerate.go
- avgsamplerate_test.go
- avgsamplewithmin.go
- avgsamplewithmin_test.go
- perkeythroughput.go
- perkeythroughput_test.go
- totalthroughput.go
- totalthroughput_test.go
It can be useful to put an upper bound on the memory used by the dynamic sampler, especially if you don't have control over the keys being submitted. If `MaxKeys` is set, enforce a maximum number of keys when collecting counts.
> Add MaxKeys option to AvgSampleRate sampler

- avgsamplerate.go
- avgsamplerate_test.go
- avgsamplewithmin.go
- doc.go
- dynsampler.go
- emasamplerate.go
- emasamplerate_test.go
- onlyonce.go
- perkeythroughput.go
- static.go
- totalthroughput.go
Losing sampler state between process restarts can be problematic, depending on the application. Adds a SaveState/LoadState interface to serialize and load state, and an initial implementation in AvgSampleRate.
> Add state persistence interface

- avgsamplerate_test.go
- emasamplerate_test.go
Was curious when, after deploying the EMASampler against our shepherd dataset, the actual average sample rate dropped to 30-40 from ~45-55. 50 is our target sample rate there. Is the EMA doing something wrong? Then I remembered we don't really test whether the dynamic sampler hits the target rate, so I added some tests to help answer this question.
> Add tests of target rate

- avgsamplerate_test.go
- emasamplerate.go
- emasamplerate_test.go
Adapting the AvgSampleRate implementation, which uses integers, to the Exponential Moving Average, which uses floats, introduced some inaccuracies with very small counts, which end up in the EMA at < 1. This results in their log being < 0, and skews `logSum` to be smaller than it would have been computed in the AvgSampleRate implementation. All this adds up to less accurate sample rate calculations when counts are small or there are a lot of keys with counts < 1. This change puts a floor on the EMA counts at 1 for the purposes of doing the log curve mapping.
I added two tests:
- TestEMASampleUpdateMapsSparseCounts
- TestAvgSampleUpdateMapsSparseCounts
These should be equal, but before my EMASampleRate changes, the EMA test got a sample rate of 5 while the AvgSampleRate test got a sample …
> [emasamplerate] Fix inaccuracies with low throughputs/small counts

- .circleci/config.yml
- go.mod
- go.sum
Updates go to v1.17.
- Closes #18 
- updates go default version to v1.17 in circleci workflows
- drops testing against go 1.10 and 1.11
- matrix'd tests for Go 1.12 - 1.17
- updated to use Circle's "new" cimg/go images
- [migrated to Go modules](https://go.dev/blog/migrating-to-go-modules)
- renamed the job _and_ workflow to "test" because that's all we're doing here
> Update go version in circleci workflows

- .circleci/config.yml
- updates internal issue https://github.com/honeycombio/telemetry-team/issues/381
- updates buildevents orb from [0.2.3](https://github.com/honeycombio/buildevents-orb/releases/tag/v0.2.3) to [0.9.0](https://github.com/honeycombio/buildevents-orb/releases/tag/v0.9.0). There are a [ton of changes](https://github.com/honeycombio/buildevents-orb/compare/v0.2.3...v0.9.0).
- not seen here but rather in CircleCI Environment Variables, `BUILDEVENT_APIKEY` was updated to a Telemetry team key, and `BUILDEVENT_APIHOST` was removed to use the default `https://api.honeycomb.io/`.
> maint: update buildevents orb and move datasets

- .circleci/config.yml
- 1.12 has been failing in CI and is ancient
- drop versions released prior to 2021 (could be even more aggressive)
> maint: drop versions of go below 1.16

- .circleci/config.yml
- Makefile
- RELEASING.md
- Anemic releasing docs. Let's bring it in-line with how we're releasing other Go libraries.
- added our usual release automation CI job (and put its smarts into a Makefile)
- added a test target to the Makefile to match other Go libraries, and config CI to record test results
- added RELEASING so the next human that needs to pull the release lever has some guidance
> ci: add usual release procedures to this project

- .circleci/config.yml
- Circle CI wouldn't run the new `publish_github` job.
- The "always match" filter needed to be added to the `setup` job else it wouldn't run for tagging events and thereby prevent `publish_github` from running.
- Use the `go` executor instead of `github` so we can have the make command.
- Arrange for `publish_github` after tests pass because we shouldn't release things that could be broken!
> ci: fix releasing

- blocklist_test.go
This is re: https://github.com/honeycombio/dynsampler-go/pull/45#issuecomment-1458856457
The original code has a rare race condition:
1) On line 180, the `currentIndex` is loaded
2) Context switch to where `currentIndex` is incremented
3) `IncrementKey` is called on the updated index
4) `AggregateCounts` is called on an old `currentIndex`. This is undefined behavior, as `currentIndex` is assumed to be monotonically increasing. 
To validate that this race condition was fixed, I wrote a script that ran the test 100 times.
With the previous code, I observed 7 failures out of 100 runs.
With the new code, I observed 0 failures out of 100 runs.
Small change to unit tests.
> fix: Fix flaky blocklist test

- avgsamplerate.go
- avgsamplerate_test.go
- avgsamplewithmin.go
- dynsampler.go
- emasamplerate.go
- onlyonce.go
- perkeythroughput.go
- static.go
- totalthroughput.go
- windowedthroughput.go
This PR adjusts the `kent.event_counts` branch (see #53) to include a Stop() function so that the samplers can be shut down properly. This is currently only useful in tests.
- Add stop function.
> feat: Add Stop() function to shut down a sampler

- .circleci/config.yml
- go.mod
This updates the Go versions supported and tested by this module to go 1.17 and above.
> maint: bump the go versions we support

- emathroughput.go
- emathroughput_test.go
- genericsampler_test.go
This adds a new sampler type, an EMAThroughput sampler.
The EMASampleRate sampler requires specifying a desired sample rate. But more often, what someone would like to do is specify a given throughput. The WindowedThroughput sampler does that, but does so at the cost of maintaining a buffer of N previous sample rates, each of which is of equal weight.
The EMAThroughput sampler maintains a diminishing moving average of samples over time; older data is of less weight than current data. It also doesn't need to maintain any extra buffers. 
Fixes #51.
> feat: EMAThroughput sampler

- avgsamplerate.go
- avgsamplewithmin.go
- dynsampler.go
- emasamplerate.go
- emathroughput.go
- onlyonce.go
- perkeythroughput.go
- static.go
- totalthroughput.go
- windowedthroughput.go
To date, the samplers have had no way of getting any metrics from them, which has sometimes made it hard to support. This adds a simple GetMetrics call that retrieves a map of named metrics on request. 
GetMetrics returns a map of metrics about the sampler's performance. All values are returned as int64; counters are cumulative and the names always end with "_count", while gauges are instantaneous with no particular naming convention. All names are prefixed with the string passed in.
- Add GetMetrics function to Sampler interface and all samplers
> feat: Add metrics counter retrieval

- emathroughput.go
- When testing the EMAThroughput sampler, I noticed different results than I expected with longer times for AdjustmentInterval. This turned out to be a bug in the sampler's math -- a divide instead of a multiply. It got the correct result with a time of 1 second, which was the default.
- Change `/` to `*` and fix comment.
> fix: Correct EMAThroughput math error

- CHANGELOG.md
Prep for 0.5.1 release.
Also fixes a couple of bad links in the previous changelog.
> rel: Prep 0.5.1

- windowedthroughput.go
- A "flaky" test in Refinery would fail occasionally with a race condition in WindowedSampler. This fixes it.
- Use a local temporary variable instead of modifying the count on the fly, then write it during the existing lock periods.
> fix: race condition in WindowedThroughput sampler

- genericsampler_test.go
- totalthroughput.go
- windowedthroughput.go
- This is instead of #69 which has a conflict I can't resolve and don't want to wait for.
- @yizzlez still gets credit for the fix
> fix: allow throughput samplers to have non-integer rates

- avgsamplerate.go
- avgsamplerate_test.go
- avgsamplewithmin.go
- avgsamplewithmin_test.go
- dynsampler.go
- emasamplerate.go
- emasamplerate_test.go
- emathroughput.go
- emathroughput_test.go
- onlyonce.go
- perkeythroughput.go
- static.go
- totalthroughput.go
- windowedthroughput.go
Generating the same metric name on each call to GetMetrics creates unnecessary heap allocation. This PR memoize the result after the first call to allow reuse of those keys
- add metric key names to the Sampler struct
- memoize the result after first call
- add tests and benchmarks
I didn't change the GetMetrics signature to avoid breaking changes to the library
```
**OLD**
goos: darwin
goarch: arm64
pkg: github.com/honeycombio/dynsampler-go
cpu: Apple M2 Max
BenchmarkEMAThroughputGetMetrics-12    	51280945	      218.2 ns/op	    376 B/op	      7 allocs/op
PASS
ok  	github.com/honeycombio/dynsampler-go	11.640s
**NEW**
goos: darwin
goarch: arm64
pkg: github.com/honeycombio/dynsampler-go
cpu: Apple M2 Max
BenchmarkEMAThroughputGetMetrics-12    	94783080	      109.9 ns/op	    256 B/op	      2 …
```
> perf: pre-compute metric keys

- .circleci/config.yml
- our Go executor takes a minor version as param
> fix: our Go executor takes a minor version as param

- .circleci/config.yml
There are security vulnerability in older Go versions. We should not support them.
It's also hard to manage `ghr` version used in our release process. I opt to use the official github image from circleci.
- drop Go 17-19 from testing matrix
- use `cibuild/github` image for `Publish Github Release` step
- Remove unused code in Makefile
> maint: update release process

- windowedthroughput.go
- windowedthroughput_test.go
We have a lock around some but not all fields on this struct... what?
Just move the lock above all field updates.
> fix: fix incorrect locking in WindowedThroughput

- avgsamplerate.go
- avgsamplerate_test.go
- avgsamplewithmin.go
- avgsamplewithmin_test.go
- emasamplerate.go
- emasamplerate_test.go
- emathroughput.go
- emathroughput_test.go
- totalthroughput.go
- totalthroughput_test.go
- windowedthroughput.go
- windowedthroughput_test.go
Refinery samplers write to GoalSampleRate at runtime when the cluster size changes, but this code's concurrency controls assume it's an immutable value that doesn't need protection.
Adds appropriate locking and a Set method so we can update GoalSampleRate without external locking.
> feat: add SetGoalSampleRate method
